Hw03 frequency analysis
dostrovskiy/otus-golang-home-work pull request #3
Opened 2024-09-15 07:14 UTC by dostrovskiy

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-17 09:33 UTC, ityulkanov commented on hw03_frequency_analysis/top_test.go
> +			"не",        // 4
По условиям ДЗ тесты модифицировать нельзя. Просто добавьте флаг и переведите его в true

2024-09-17 09:36 UTC, ityulkanov requested changes
Пожалуйста, поправьте тесты в соответствии с комментарием

2024-09-18 10:58 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +	return Top10Hard(text, false)
Если hard всегда false, тогда вообще непонятен смысл функции wrapperа. Кмк тут мы смело можем удалить top10hard и всю логику оставить в top10.

2024-09-18 11:00 UTC, ityulkanov commented on hw03_frequency_analysis/top_simplewords_test.go
тесты касающиеся одного файла (main.go для примера) в идеале было бы хранить в одном и том же файлы, чтобы избежать излишнего дублирования кода. Да и просто смущает, когда 3 файла, тестируют один и тот же top10 )

2024-09-18 14:29 UTC, dostrovskiy commented on hw03_frequency_analysis/top.go
> +	return Top10Hard(text, false)
Это что-то типа overload-а функций, чтобы можно было вызвать функцию с одним параметром, а второй будет иметь значение по умолчанию.

2024-09-19 09:01 UTC, dostrovskiy commented on hw03_frequency_analysis/top_simplewords_test.go
Исправил.

2024-09-21 14:40 UTC, dostrovskiy commented on hw03_frequency_analysis/top.go
> +	return Top10Hard(text, false)
Исправил.

2024-09-22 08:56 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +func Top10(text string, hard bool) []string {
Смотрю. А зачем в top10 было оставлять второй параметр, раз он у нас все равно false?

2024-09-22 08:57 UTC, ityulkanov commented on hw03_frequency_analysis/top_test.go
> +		require.Len(t, Top10("", false), 0)
```suggestion
		require.Len(t, Top10(""), 0)
```

2024-09-22 08:57 UTC, ityulkanov commented on hw03_frequency_analysis/top_test.go
> +			require.Equal(t, expected, Top10(text, true))
```suggestion
			require.Equal(t, expected, Top10(text))
```

2024-09-22 08:57 UTC, ityulkanov commented on hw03_frequency_analysis/top_test.go
> +			require.Equal(t, expected, Top10(text, false))
```suggestion
			require.Equal(t, expected, Top10(text))
```

2024-09-22 08:57 UTC, ityulkanov commented on hw03_frequency_analysis/top_test.go
> +			result := Top10(tc.input, tc.hard)
```suggestion
			result := Top10(tc.input)
```

2024-09-22 08:57 UTC, ityulkanov commented on hw03_frequency_analysis/top_test.go
> +		hard     bool
```suggestion
```

2024-09-22 09:17 UTC, dostrovskiy commented on hw03_frequency_analysis/top.go
> +func Top10(text string, hard bool) []string {
Исправил.

2024-09-22 09:56 UTC, ityulkanov approved these changes

2024-09-22 10:21 UTC, merged