Hw08 envdir tool
dostrovskiy/otus-golang-home-work pull request #8
Opened 2024-11-21 12:50 UTC by dostrovskiy

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-11-23 09:52 UTC, vladislavmass requested changes

2024-11-23 09:52 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +		eval, err := readEnv(dir, file)
Не вижу обработки = в имени файла

2024-11-23 09:52 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +	return &EnvValue{Value: strings.TrimRightFunc(string(bs), unicode.IsSpace)}, nil
По условия задания нужно удалить пробел и табуляцию, все остальное удалять не нужно

2024-11-23 09:52 UTC, vladislavmass commented on hw08_envdir_tool/executor.go
> +	return execCmd.ProcessState.ExitCode()
В корне не верный подход. Любой код отличный от 0 вызовет ошибку exec.ExitError и мы пойдем по блоку где err!=nil

2024-11-23 09:57 UTC, vladislavmass commented on hw08_envdir_tool/executor.go
> +		log.Fatalf("execution error: %+v\n", err)
Log.Fatal внутри себя вызовет os.Exit(1) поэтому поле этой строки код недостижим

2024-11-23 17:15 UTC, dostrovskiy commented on hw08_envdir_tool/env_reader.go
> +		eval, err := readEnv(dir, file)
Добавил.

2024-11-23 17:17 UTC, dostrovskiy commented on hw08_envdir_tool/env_reader.go
> +	return &EnvValue{Value: strings.TrimRightFunc(string(bs), unicode.IsSpace)}, nil
Поменял функцию unicode.IsSpace на собственную, которая проверяет только пробелы и табы.

2024-11-23 17:18 UTC, dostrovskiy commented on hw08_envdir_tool/executor.go
> +		log.Fatalf("execution error: %+v\n", err)
Удалил лишний return 1.

2024-11-23 19:07 UTC, dostrovskiy commented on hw08_envdir_tool/executor.go
> +	return execCmd.ProcessState.ExitCode()
Исправил.

2024-11-24 10:29 UTC, vladislavmass approved these changes

2024-11-24 10:29 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +	if strings.Contains(file.Name(), "=") {
Немного странный подход, проверка на то, что это файл а не директория значит в метода выше, а вариация имени файла тут

2024-11-24 10:29 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +	return &EnvValue{Value: strings.TrimRightFunc(string(bs), shouldTrim)}, nil
Тут бы хватило TrimRight(string(bs),"\t "

2024-11-24 16:58 UTC, dostrovskiy commented on hw08_envdir_tool/env_reader.go
> +	if strings.Contains(file.Name(), "=") {
Да. Исправил.

2024-11-24 17:01 UTC, dostrovskiy commented on hw08_envdir_tool/env_reader.go
> +	return &EnvValue{Value: strings.TrimRightFunc(string(bs), shouldTrim)}, nil
Интересно. Не заметил сразу, что в TrimRight можно передать set символов, а не один. Исправил.

2024-11-25 14:09 UTC, merged